const LOOKUP = {
  // Browser
  'Google Chrome':      'Browser',
  'Microsoft Edge':     'Browser',
  'Firefox':            'Browser',
  'Brave':              'Browser',
  'Brave Browser':      'Browser',
  'Opera':              'Browser',
  'Opera GX':           'Browser',
  'Vivaldi':            'Browser',
  'Arc':                'Browser',
  'Tor Browser':        'Browser',

  // Development
  'VS Code':                  'Development',
  'Visual Studio Code':       'Development',
  'Visual Studio':            'Development',
  'Android Studio':           'Development',
  'IntelliJ IDEA':            'Development',
  'IntelliJ IDEA Ultimate':   'Development',
  'PyCharm':                  'Development',
  'PyCharm Professional':     'Development',
  'WebStorm':                 'Development',
  'PhpStorm':                 'Development',
  'CLion':                    'Development',
  'GoLand':                   'Development',
  'Rider':                    'Development',
  'DataGrip':                 'Development',
  'RubyMine':                 'Development',
  'AppCode':                  'Development',
  'Xcode':                    'Development',
  'Sublime Text':             'Development',
  'Atom':                     'Development',
  'Notepad++':                'Development',
  'Vim':                      'Development',
  'Neovim':                   'Development',
  'Emacs':                    'Development',
  'Windows Terminal':         'Development',
  'Powershell':               'Development',
  'PowerShell 7':             'Development',
  'Command Prompt':           'Development',
  'Git Bash':                 'Development',
  'GitHub Desktop':           'Development',
  'Sourcetree':               'Development',
  'Fork':                     'Development',
  'GitKraken':                'Development',
  'Postman':                  'Development',
  'Insomnia':                 'Development',
  'Hoppscotch':               'Development',
  'Figma':                    'Development',
  'TablePlus':                'Development',
  'DBeaver':                  'Development',
  'Sequel Pro':               'Development',
  'Docker Desktop':           'Development',
  'Proxyman':                 'Development',
  'Charles':                  'Development',
  'Cyberduck':                'Development',
  'FileZilla':                'Development',
  'WinSCP':                   'Development',
  'Claude':                   'Development',

  // Communication
  'Slack':              'Communication',
  'Discord':            'Communication',
  'Microsoft Teams':    'Communication',
  'Zoom':               'Communication',
  'Skype':              'Communication',
  'Telegram':           'Communication',
  'WhatsApp':           'Communication',
  'Signal':             'Communication',
  'Viber':              'Communication',
  'Line':               'Communication',
  'Outlook':            'Communication',
  'Microsoft Outlook':  'Communication',
  'Thunderbird':        'Communication',
  'Mail':               'Communication',
  'Gmail':              'Communication',
  'Google Meet':        'Communication',
  'Webex':              'Communication',
  'Rocket.Chat':        'Communication',
  'Mattermost':         'Communication',

  // Productivity
  'Microsoft Excel':        'Productivity',
  'Microsoft Word':         'Productivity',
  'Microsoft PowerPoint':   'Productivity',
  'Microsoft OneNote':      'Productivity',
  'Microsoft Access':       'Productivity',
  'Microsoft Publisher':    'Productivity',
  'Notion':                 'Productivity',
  'Obsidian':               'Productivity',
  'Roam Research':          'Productivity',
  'Logseq':                 'Productivity',
  'Todoist':                'Productivity',
  'TickTick':               'Productivity',
  'Things':                 'Productivity',
  'OmniFocus':              'Productivity',
  'Asana':                  'Productivity',
  'Trello':                 'Productivity',
  'Linear':                 'Productivity',
  'Jira':                   'Productivity',
  'Confluence':             'Productivity',
  'Airtable':               'Productivity',
  'Notepad':                'Productivity',
  'Adobe Acrobat':          'Productivity',
  'Acrobat':                'Productivity',
  'LibreOffice Writer':     'Productivity',
  'LibreOffice Calc':       'Productivity',
  'LibreOffice Impress':    'Productivity',
  'Google Docs':            'Productivity',
  'Google Sheets':          'Productivity',
  'Google Slides':          'Productivity',

  // Entertainment
  'Spotify':              'Entertainment',
  'VLC':                  'Entertainment',
  'VLC media player':     'Entertainment',
  'Netflix':              'Entertainment',
  'YouTube':              'Entertainment',
  'YouTube Music':        'Entertainment',
  'Apple Music':          'Entertainment',
  'iTunes':               'Entertainment',
  'foobar2000':           'Entertainment',
  'Winamp':               'Entertainment',
  'MPC-HC':               'Entertainment',
  'PotPlayer':            'Entertainment',
  'mpv':                  'Entertainment',
  'KMPlayer':             'Entertainment',
  'Windows Media Player': 'Entertainment',
  'Groove Music':         'Entertainment',
  'Movies & TV':          'Entertainment',
  'Prime Video':          'Entertainment',
  'Disney+':              'Entertainment',
  'Plex':                 'Entertainment',
  'Jellyfin':             'Entertainment',
  'Kodi':                 'Entertainment',
  'OBS Studio':           'Entertainment',
  'Twitch':               'Entertainment',

  // Gaming
  'Steam':                'Gaming',
  'Epic Games Launcher':  'Gaming',
  'Battle.net':           'Gaming',
  'Riot Client':          'Gaming',
  'EA App':               'Gaming',
  'Origin':               'Gaming',
  'GOG Galaxy':           'Gaming',
  'Xbox':                 'Gaming',
  'Xbox Game Bar':        'Gaming',
  'Minecraft':            'Gaming',
  'Minecraft Launcher':   'Gaming',
  'Fortnite':             'Gaming',
  'Valorant':             'Gaming',
  'League of Legends':    'Gaming',
  'Roblox':               'Gaming',
  'Roblox Player':        'Gaming',
  'Counter-Strike 2':     'Gaming',
  'Dota 2':               'Gaming',
  'Overwatch':            'Gaming',
  'Overwatch 2':          'Gaming',
  'Apex Legends':         'Gaming',
  'Hearthstone':          'Gaming',
  'World of Warcraft':    'Gaming',
  'PUBG':                 'Gaming',

  // Social
  'Instagram':    'Social',
  'Twitter':      'Social',
  'X':            'Social',
  'Facebook':     'Social',
  'TikTok':       'Social',
  'Snapchat':     'Social',
  'Reddit':       'Social',
  'Pinterest':    'Social',
  'LinkedIn':     'Social',
  'BeReal':       'Social',

  // Utility
  'File Explorer':      'Utility',
  'Task Manager':       'Utility',
  'Control Panel':      'Utility',
  'Settings':           'Utility',
  'Registry Editor':    'Utility',
  '7-Zip':              'Utility',
  'WinRAR':             'Utility',
  'Rufus':              'Utility',
  'Etcher':             'Utility',
  'VMware Workstation': 'Utility',
  'VirtualBox':         'Utility',
  'TeamViewer':         'Utility',
  'AnyDesk':            'Utility',
  'CPU-Z':              'Utility',
  'GPU-Z':              'Utility',
  'HWiNFO':             'Utility',
  'MSI Afterburner':    'Utility',
  'ShareX':             'Utility',
  'Greenshot':          'Utility',
}

// Substring fallback rules — checked in order, first match wins
const SUBSTR_RULES = [
  ['chrome',      'Browser'],
  ['firefox',     'Browser'],
  ['edge',        'Browser'],
  ['brave',       'Browser'],
  ['opera',       'Browser'],
  ['safari',      'Browser'],
  ['browser',     'Browser'],
  ['vivaldi',     'Browser'],

  ['code',        'Development'],
  ['studio',      'Development'],
  ['terminal',    'Development'],
  ['powershell',  'Development'],
  ['console',     'Development'],
  ['postman',     'Development'],
  ['figma',       'Development'],
  ['gitk',        'Development'],
  ['sourcetree',  'Development'],
  ['datagrip',    'Development'],
  ['pycharm',     'Development'],
  ['webstorm',    'Development'],

  ['slack',       'Communication'],
  ['discord',     'Communication'],
  ['teams',       'Communication'],
  ['zoom',        'Communication'],
  ['telegram',    'Communication'],
  ['whatsapp',    'Communication'],
  ['outlook',     'Communication'],
  ['skype',       'Communication'],
  ['signal',      'Communication'],
  ['mail',        'Communication'],
  ['meet',        'Communication'],

  ['excel',       'Productivity'],
  ['word',        'Productivity'],
  ['powerpoint',  'Productivity'],
  ['onenote',     'Productivity'],
  ['notion',      'Productivity'],
  ['obsidian',    'Productivity'],
  ['todoist',     'Productivity'],
  ['ticktick',    'Productivity'],
  ['notepad',     'Productivity'],
  ['acrobat',     'Productivity'],
  ['libreoffice', 'Productivity'],
  ['docs',        'Productivity'],
  ['sheets',      'Productivity'],

  ['spotify',     'Entertainment'],
  ['vlc',         'Entertainment'],
  ['netflix',     'Entertainment'],
  ['youtube',     'Entertainment'],
  ['music',       'Entertainment'],
  ['player',      'Entertainment'],
  ['obs',         'Entertainment'],
  ['twitch',      'Entertainment'],
  ['plex',        'Entertainment'],
  ['media',       'Entertainment'],

  ['steam',       'Gaming'],
  ['epic',        'Gaming'],
  ['game',        'Gaming'],
  ['riot',        'Gaming'],
  ['minecraft',   'Gaming'],
  ['fortnite',    'Gaming'],
  ['roblox',      'Gaming'],
  ['valorant',    'Gaming'],
  ['league',      'Gaming'],
  ['xbox',        'Gaming'],
  ['launcher',    'Gaming'],

  ['instagram',   'Social'],
  ['twitter',     'Social'],
  ['facebook',    'Social'],
  ['tiktok',      'Social'],
  ['reddit',      'Social'],
  ['linkedin',    'Social'],

  ['explorer',    'Utility'],
  ['manager',     'Utility'],
  ['settings',    'Utility'],
  ['control',     'Utility'],
]

function guessCategory(appName) {
  if (!appName) return 'Other'
  if (LOOKUP[appName]) return LOOKUP[appName]
  const lower = appName.toLowerCase()
  for (const [substr, cat] of SUBSTR_RULES) {
    if (lower.includes(substr)) return cat
  }
  return 'Other'
}

module.exports = { guessCategory }
